name: Deploy Flask API to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package and deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_FLASK_FUNCTION_NAME: ${{ secrets.LAMBDA_FLASK_FUNCTION_NAME }}
        run: |
          cd backend
          zip -r9 ../function.zip *  # Empaqueta todo en backend y coloca el ZIP en el directorio superior
          aws lambda update-function-code \
            --function-name $LAMBDA_FLASK_FUNCTION_NAME \
            --zip-file fileb://../function.zip

      - name: Add API Gateway permissions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_FLASK_FUNCTION_NAME: ${{ secrets.LAMBDA_FLASK_FUNCTION_NAME }}
        run: |
          aws lambda add-permission \
            --function-name $LAMBDA_FLASK_FUNCTION_NAME \
            --statement-id apigateway-access \
            --action lambda:InvokeFunction \
            --principal apigateway.amazonaws.com
